const data = [{
    "branch_id": "BR101",
    "product_id": "",
    "product_type": "DIALYSIS",
    "product_cost": 5000,
    "product_name": {
        "product_id": "P5",
        "product_name": "Hemodiafiltration  5008 FX 80",
        "unit": "Nos",
        "dialysis": "Y",
        "lab": "N",
        "pharmacy": "N",
        "stock_in_hand": "300",
        "min_stock": "30",
        "max_stock": "3000",
        "reorder_level": "100",
        "product_type": "DIALYSIS",
        "selling_price": "5000",
        "with_effect_from": "2022-01-13",
        "curr_date": null
    },
    "product_bill_qty": 2,
    "product_total_value": 10000,
    "charge1": 0,
    "charge2": 0,
    "charge3": 0,
    "cgremark1": "",
    "cgremark2": "",
    "cgremark3": "",
    "gross_inv_amount": 10000,
    "dscount1": 0,
    "dscount2": 0,
    "dscount3": 0,
    "dsremark1": "",
    "dsremark2": "",
    "dsremark3": "",
    "totaldiscount": 0,
    "netamount": 10000,
    "netbalance": 0,
    "netpaid": 0,
    "updated_by": "MA101"
}];